
before_install:
- sudo apt-get update 
- sudo apt-get install texlive-latex-extra
script:
- mkdir _build
- pdflatex -output-directory _build ./hello.tex
deploy:
  provider: releases
  api_key: 62ee449c5dff4f68d117fcb54631a90d4d9b55d4
  file:
    - ./_build/hello.pdf
  skip_cleanup: true
  on:
    tags: true
    branch: master
