
before_install:
- sudo apt-get update 
- sudo apt-get install texlive-latex-extra
script:
- mkdir _build
- pdflatex -output-directory _build ./hello.tex
deploy:
  provider: releases
  api_key: 3e266a8796b9c761149c39f7b309888fe7722482
  file:
    - ./_build/hello.pdf
  skip_cleanup: true
  on:
    tags: true
    branch: master
